### ISSUE TITLE
Async Patterns: RxJS, Promises async/await, callbacks, async generators

### ISSUE THREAD

**Issue by PatrickJS** [rectanglepodcast-com/rectanglepodcast.com#19]
I need to complicate my code

**Comment by ducin** [comment]
If the topic is to complicate async code, include redux-saga and redux-observables as main characters 🔥

**Comment by PatrickJS** [comment]
oh yeah saga pattern. still a good pattern to know

**Comment by PatrickJS** [comment]
we might change this to async only since a lot of stuff will be covered by https://github.com/rectanglepodcast-com/rectanglepodcast.com/issues/21
