### ISSUE TITLE
Rectangle Episode 4: Embracing Laziness with streams

### ISSUE THREAD

**Issue by ducin** [rectanglepodcast-com/rectanglepodcast.com#21]
With the new tc39 proposal shipped in the browser, the way we write days processing could change drastically - from eager-first and lazy only on framework level - to lazy-first and eager only when it's required.

https://github.com/tc39/proposal-iterator-helpers

Thanks to these simple utility functions we could utilize writing more performance data processing almost for free, e.g. instead of

```tsx
arr.map(...)
```

go

```tsx
arr.values().map(...)
```

and that's already lazy. Only the consumer can make the consumotion eager. Now imagine all that we write is evaluated in a lazy fashion (all are iterators/generators underneath). And the code itself is almost as easy as it is today...

IMO this proposal could be a game changer. So that's the topic.

**Comment by PatrickJS** [comment]
https://github.com/ReactiveX/rxjs

https://github.com/ReactiveX/IxJS

**Comment by nmn** [comment]
Also:

- Generator functions
- Async Generator functions
- Promises, async-await, issues.
- [co](https://github.com/tj/co)
- [Structured concurrency with Effection](https://frontside.com/effection)
  - [Structured concurrency in Swift](https://developer.apple.com/tutorials/app-dev-training/managing-structured-concurrency)

**Comment by PatrickJS** [comment]
recording is here
https://x.com/PatrickJS__/status/1761594206794235967?s=20
